import React from 'react';
import { Link } from 'react-router-dom';
import { Field, reduxForm } from 'redux-form';

class PostsForm extends React.Component {
	renderInput = ({ input, meta, label }) => {
		const className = `field ${meta.error && meta.touched ? 'error' : ''}`;
		return (
			<div className={className}>
				<label htmlFor="">{label}</label>
				<input type="text" {...input} />
				<div>
					{/* to show error message generated by validation form */}
					{this.renderError(meta)}
				</div>
			</div>
		);
	};

	renderError = ({ error, touched }) => {
		if (error && touched) {
			return <div className="ui error message">{error}</div>;
		}
	};

	onSubmit = formValues => {
		this.props.onSubmit(formValues);
	};
	render() {
		console.log(this.props.initialValues);
		return (
			<div>
				<form
					className="ui form error"
					// * handleSubmit comes from redux form, exactly from this.props
					onSubmit={this.props.handleSubmit(this.onSubmit)}
				>
					<Field label="Title" name="title" component={this.renderInput} />
					<Field
						label="Category"
						name="categories"
						component={this.renderInput}
					/>
					<Field
						label="Description"
						name="content"
						component={this.renderInput}
					/>
					<button type="submit" className="ui primary button">
						{this.props.buttonLabel}
					</button>
					<Link to="/" className="ui button">
						Cancel
					</Link>
				</form>
			</div>
		);
	}
}

//will check if all required fields are entered.
const validate = formValues => {
	//console.log(formValues) -> { title: 'assdasd', category: 'dasdasdasd', description: 'asdasdasd' }
	const errors = {};
	//validate the input from the formValues.
	if (!formValues.title) {
		errors.title = 'Please enter a title.';
	}
	if (!formValues.categories) {
		errors.categories = 'Please enter at least 1 category.';
	}
	if (!formValues.content) {
		errors.content = 'Please enter description.';
	}
	// if errors object is empty then it is fine to submit the form
	return errors;
};

//Connect reduxForm to component.

export default reduxForm({ form: 'newPostsForm', validate })(PostsForm);
